CREATE TABLE "GCG_5907_Lines"  (
 "UserID" CHAR(8),
 "JS" CHAR(10),
 "Job" CHAR(6),
 "Suffix" CHAR(3),
 "Seq" CHAR(6),
 "Part" CHAR(20),
 "Location" CHAR(2),
 "Part17" CHAR(17),
 "Rev" CHAR(3),
 "Description" CHAR(30),
 "Qty_Required" NUMERIC(12,4),
 "RunTotalRequired" NUMERIC(12,4),
 "PartLoc" CHAR(22),
 "SC" CHAR(12),
 "Qty_Onhand" NUMERIC(12,4),
 "Date_Due" DATE,
 "Qty_Avail" NUMERIC(12,4),
 "Qty_Short" NUMERIC(12,4) );
